version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=apcore_user
      - POSTGRES_PASSWORD=apcore_pass
      - POSTGRES_DB=apcore_db
      - POSTGRES_PORT=5432
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE_AT=24h
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: apcore_db
      POSTGRES_USER: apcore_user
      POSTGRES_PASSWORD: apcore_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
