version: "3.8"

services:
  app:
    build:
      context: .
    image: ghcr.io/arian-press2015/apcore:latest
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=apcore_user
      - POSTGRES_PASSWORD=apcore_pass
      - POSTGRES_DB=apcore_db
      - POSTGRES_PORT=5432
      - JWT_SECRET=68t65tr8f64e3ww44d56y7ygu0h8ip9obn987
      - JWT_EXPIRE_AT=24h
      - LOGGER_ELASTIC_ENABLED=false
      - LOGGER_FILE_ENABLED=true
      - ELASTICSEARCH_URL=
      - ELASTICSEARCH_USERNAME=
      - ELASTICSEARCH_PASSWORD=
      - ELASTICSEARCH_INDEX=
      - REDIS_URL=redis:6379
      - SMS_API_URL=https://api.sms.ir
      - SMS_API_KEY=fhX610bkEUgapa3bDRgK0ucx98tuXGoM5r2X9SFsEyBHmVjpeelDue6T81cQTiIX
      - SMS_LINE_NUMBER=30007732008897
    volumes:
      - ./public:/app/public
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: apcore_db
      POSTGRES_USER: apcore_user
      POSTGRES_PASSWORD: apcore_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    restart: always

volumes:
  postgres_data:
